import type { Metadata } from 'next';
import PageHeader from '../../components/pageHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <PageHeader title='로그인' />
        {children}
      </body>
    </html>
  );
}
