'use client';
// import type { Metadata } from 'next';
import PageHeader from '../../components/pageHeader';
import { AnimatePresence, motion } from 'framer-motion';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <PageHeader title='로그인' />
        <AnimatePresence mode='wait'>
          <motion.div
            initial='initial'
            animate='in'
            exit='out'
            transition={{ duration: 0.5 }}
            variants={{
              initial: {
                opacity: 0,
              },
              in: {
                opacity: 1,
              },
              out: {
                opacity: 0,
              },
            }}
          >
            {children}
          </motion.div>
        </AnimatePresence>
      </body>
    </html>
  );
}
