import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';
import PageHeader from '../../components/pageHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function withdrawLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <Toaster position='bottom-center' reverseOrder={false} />
        <PageHeader title='회원탈퇴' />
        {children}
      </body>
    </html>
  );
}
