import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { geistMono, geistSans, Pretendard, Manseh } from "../font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${Pretendard.variable} ${Manseh.variable} antialiased`}
      >
        {props.children}
      </body>
    </html>
  );
}
