import type { Metadata } from 'next';
import './globals.css';
// import localFont from 'next/font/local';

// const manSehFont = localFont({
//   src: '../public/fonts/ManSeh.ttf',
//   variable: '--font-manSeh',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
