import type { Metadata } from 'next';
import SignUpProviders from '../../components/provider/SignUpProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <SignUpProviders>{children}</SignUpProviders>
      </body>
    </html>
  );
}
