import type { Metadata } from 'next';
import SignUpProviders from '../../components/provider/SignUpProviders';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='mx-auto'>
        <SignUpProviders>
          <Toaster position='bottom-center' reverseOrder={false} />
          {children}
        </SignUpProviders>
      </body>
    </html>
  );
}
