name: Synchronize to forked repo
on:
  push:
    branches:
      - develop

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://tnemnorivnelee:${{ secrets.AUTO_ACTIONS }}@github.com/tnemnorivnelee/Hanmo-front
          git config user.name tnemnorivnelee
          git config user.email ${{ secrets.EMAIL }}
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo develop
      
      - name: Clean up
        run: |
          git remote remove forked-repo
